
services:
  php:
    build: ./docker/php
    user: 1000:1000
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:8000"
    networks:
      - taskease
    command: "php artisan serve --host 0.0.0.0"

  db:
    image: mysql
    restart: always
    ports:
      - "8082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Taskease
      MYSQL_DATABASE: Taskease
      MYSQL_USER: Taskease
      MYSQL_PASSWORD: Taskease
    volumes:
      - "./docker/db/data:/var/lib/mysql"
    networks:
      - taskease

networks:
  taskease:
    name: taskease
  
